package Client.Fonctionnalite;

import Client.ClientUI;

import javax.swing.*;
import java.awt.*;

public class UIHelper {

    private static JPanel contentPane;
    private static JPanel topPanel;
    private static JPanel sidebarPanel;

    public static void setupUI(ClientUI clientUI) {

        Dimension localScreenSize = Toolkit.getDefaultToolkit().getScreenSize();

        clientUI.setSize((int) (localScreenSize.getWidth() * 0.8), (int) (localScreenSize.getHeight() * 0.8));
        clientUI.setTitle("AnyDesk");
        clientUI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        clientUI.setLocationRelativeTo(null);
        clientUI.setLayout(new BorderLayout());

        contentPane = new JPanel(new BorderLayout());
        clientUI.setContentPane(contentPane);

        topPanel = createTopPanel();
        contentPane.add(topPanel, BorderLayout.NORTH);
        ClientUI.topPanel=topPanel;

        sidebarPanel = createSidebarPanel();
        contentPane.add(sidebarPanel, BorderLayout.EAST);
        ClientUI.sidebarPanel=sidebarPanel;

        JLabel screenLabel = new JLabel();
        contentPane.add(screenLabel, BorderLayout.CENTER);

        clientUI.screenLabel = screenLabel;
    }

    private static JPanel createTopPanel() {
        JPanel topPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        JLabel logoLabel = new JLabel(new ImageIcon("logo.png"));
        JLabel appNameLabel = new JLabel("AnyDesk");
        appNameLabel.setFont(new Font("Arial", Font.BOLD, 24));
        topPanel.add(logoLabel);
        topPanel.add(appNameLabel);
        return topPanel;
    }

    private static JPanel createSidebarPanel() {
        JPanel sidebarPanel = new JPanel();
        sidebarPanel.setLayout(new BoxLayout(sidebarPanel, BoxLayout.Y_AXIS));
        sidebarPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        sidebarPanel.add(new JLabel("Instructions:"));
        JTextArea instructionsArea = new JTextArea("1. Enter the code generated by the server.\n2. Click 'Connect' to start the remote session.");
        instructionsArea.setEditable(false);
        instructionsArea.setLineWrap(true);
        instructionsArea.setWrapStyleWord(true);
        sidebarPanel.add(new JScrollPane(instructionsArea));
        return sidebarPanel;
    }
}
