import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;

public class ClientUI extends JFrame implements KeyListener, MouseListener, MouseMotionListener {
    private JLabel screenLabel;
    private Timer timer;
    private RemoteInterface server;
    private String serverPassword;
    private JFileChooser fileChooser;
    private JPanel contentPane;
    private JTextField passwordField;
    JPanel centerPanel;
    JPanel sidebarPanel;
    public ClientUI() throws RemoteException {
        setTitle("AnyDesk");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // Création du panneau de contenu
        contentPane = new JPanel(new BorderLayout());
        setContentPane(contentPane);

        // Création du panneau supérieur pour le logo et le nom de l'application
        JPanel topPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        JLabel logoLabel = new JLabel(new ImageIcon("logo.png")); // Remplacez "logo.png" par le chemin de votre fichier logo
        JLabel appNameLabel = new JLabel("AnyDesk");
        appNameLabel.setFont(new Font("Arial", Font.BOLD, 24));
        topPanel.add(logoLabel);
        topPanel.add(appNameLabel);
        contentPane.add(topPanel, BorderLayout.NORTH);

        // Création du panneau central pour le champ de saisie du mot de passe
        centerPanel = new JPanel();
        centerPanel.setLayout(new BoxLayout(centerPanel, BoxLayout.Y_AXIS));
        JLabel passwordLabel = new JLabel("Enter Server Password:");
        passwordField = new JTextField(20);
        centerPanel.add(passwordLabel);
        centerPanel.add(passwordField);
        JButton connectButton = new JButton("Connect");
        connectButton.setBackground(new Color(0, 153, 204)); // Couleur de fond bleue
        connectButton.setForeground(Color.WHITE); // Texte en blanc
        connectButton.setFocusPainted(false); // Enlever le contour du bouton lorsqu'il est sélectionné
        connectButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                serverPassword = passwordField.getText();
                try {
                    if (!checkServerPassword(serverPassword)) {
                        JOptionPane.showMessageDialog(ClientUI.this, "Incorrect server password. Exiting...");
                        System.exit(0);
                    } else {
                        startScreenRefresh();
                        centerPanel.setVisible(false);
                        sidebarPanel.setVisible(false);
                    }
                } catch (RemoteException ex) {
                    ex.printStackTrace();
                }
            }
        });
        centerPanel.add(connectButton);
        contentPane.add(centerPanel, BorderLayout.WEST);


        // Création de la barre latérale à droite
        sidebarPanel = new JPanel();
        sidebarPanel.setLayout(new BoxLayout(sidebarPanel, BoxLayout.Y_AXIS));
        sidebarPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        sidebarPanel.add(new JLabel("Instructions:"));
        JTextArea instructionsArea = new JTextArea("1. Enter the code generated by the server.\n2. Click 'Connect' to start the remote session.");
        instructionsArea.setEditable(false);
        instructionsArea.setLineWrap(true);
        instructionsArea.setWrapStyleWord(true);
        sidebarPanel.add(new JScrollPane(instructionsArea));
        contentPane.add(sidebarPanel, BorderLayout.EAST);

        // Initialisation du sélecteur de fichiers
        fileChooser = new JFileChooser();

        // Connexion au serveur RMI
        try {
            Registry registry = LocateRegistry.getRegistry("192.168.137.1", 1099);
            server = (RemoteInterface) registry.lookup("remoteDesktopServer");
        } catch (Exception e) {
            System.err.println("Client exception: " + e.toString());
            e.printStackTrace();
        }

        // Ajout des autres composants et fonctionnalités (rafraîchissement d'écran, gestion des événements, etc.)
        screenLabel = new JLabel();
        contentPane.add(screenLabel, BorderLayout.CENTER);

        // Menu pour le transfert de fichiers
        JMenuBar menuBar = new JMenuBar();
        JMenu fileMenu = new JMenu("Fichier");
        JMenuItem sendFileMenuItem = new JMenuItem("Envoyer un fichier");
        sendFileMenuItem.addActionListener(new SendFileAction());
        JMenuItem receiveFileMenuItem = new JMenuItem("Recevoir un fichier");
        receiveFileMenuItem.addActionListener(new ReceiveFileAction());
        fileMenu.add(sendFileMenuItem);
        fileMenu.add(receiveFileMenuItem);
        menuBar.add(fileMenu);
        setJMenuBar(menuBar);


        // Gestion des événements de souris et de clavier
        addMouseListener(this);
        addMouseMotionListener(this);
        addKeyListener(this);

        // Dimensions de la fenêtre
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) (screenSize.width * 0.8);
        int height = (int) (screenSize.height * 0.8);
        setSize(width, height);
        setLocationRelativeTo(null);


    }

    private boolean checkServerPassword(String password) throws RemoteException {
        // Vérifier le mot de passe avec le serveur
        return server.checkPassword(password);
    }

    private void startScreenRefresh() {
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                refreshScreen();
            }
        };
        timer = new Timer(1, taskPerformer); // Rafraîchir toutes les 1 ms
        timer.start();
    }

    private void refreshScreen() {
        try {
            // Récupération de l'écran distant
            byte[] imageData = server.captureScreen();
            if (imageData != null) {
                // Convertir les données d'image en ImageIcon
                ImageIcon imageIcon = new ImageIcon(imageData);

                // Redimensionner l'image capturée en fonction de la taille de l'écran du client
                int screenWidth = Toolkit.getDefaultToolkit().getScreenSize().width;
                int screenHeight = Toolkit.getDefaultToolkit().getScreenSize().height;
                Image scaledImage = imageIcon.getImage().getScaledInstance(screenWidth, screenHeight, Image.SCALE_SMOOTH);
                ImageIcon scaledImageIcon = new ImageIcon(scaledImage);

                // Afficher l'image redimensionnée dans JLabel
                screenLabel.setIcon(scaledImageIcon);
            }
        } catch (Exception e) {
            System.err.println("Client exception: " + e.toString());
            e.printStackTrace();
        }
    }


    @Override
    public void mouseMoved(MouseEvent e) {
        try {
            int x = e.getX();
            int y = e.getY();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int screenWidth = screenSize.width;
            int screenHeight = screenSize.height;
            int labelWidth = screenLabel.getWidth();
            int labelHeight = screenLabel.getHeight();

            int remoteX = (int) ((double) x / labelWidth * screenWidth);
            int remoteY = (int) ((double) y / labelHeight * screenHeight);

            int[] tab = {remoteX, remoteY};
            server.receiveMouseEvent(tab);
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Error moving cursor on remote screen: " + ex.getMessage(), "Remote Screen Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        try {
            Point clickPoint = e.getPoint();
            int x = clickPoint.x;
            int y = clickPoint.y;

            int remoteWidth = server.getScreenWidth();
            int remoteHeight = server.getScreenHeight();
            int labelWidth = screenLabel.getWidth();
            int labelHeight = screenLabel.getHeight();

            double scaleX = (double) remoteWidth / labelWidth;
            double scaleY = (double) remoteHeight / labelHeight;

            int remoteX = (int) (x * scaleX);
            int remoteY = (int) (y * scaleY);

            remoteX = Math.max(0, Math.min(remoteX, remoteWidth - 1));
            remoteY = Math.max(0, Math.min(remoteY, remoteHeight - 1));

            server.clickMouse(remoteX, remoteY);
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Error sending mouse click to remote screen: " + ex.getMessage(), "Remote Screen Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {

        try {
            int x = e.getX();
            int y = e.getY();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int screenWidth = screenSize.width;
            int screenHeight = screenSize.height;
            int labelWidth = screenLabel.getWidth();
            int labelHeight = screenLabel.getHeight();

            int remoteX = (int) ((double) x / labelWidth * screenWidth);
            int remoteY = (int) ((double) y / labelHeight * screenHeight);

            server.mousePressed(remoteX, remoteY, e.getButton());
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Error sending mouse press to remote screen: " + ex.getMessage(), "Remote Screen Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        try {
            int x = e.getX();
            int y = e.getY();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int screenWidth = screenSize.width;
            int screenHeight = screenSize.height;
            int labelWidth = screenLabel.getWidth();
            int labelHeight = screenLabel.getHeight();

            int remoteX = (int) ((double) x / labelWidth * screenWidth);
            int remoteY = (int) ((double) y / labelHeight * screenHeight);

            server.mouseReleased(remoteX, remoteY, e.getButton());
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Error sending mouse release to remote screen: " + ex.getMessage(), "Remote Screen Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        try {
            int x = e.getX();
            int y = e.getY();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int screenWidth = screenSize.width;
            int screenHeight = screenSize.height;
            int labelWidth = screenLabel.getWidth();
            int labelHeight = screenLabel.getHeight();

            int remoteX = (int) ((double) x / labelWidth * screenWidth);
            int remoteY = (int) ((double) y / labelHeight * screenHeight);

            server.receiveMouseEvent(new int[]{remoteX, remoteY});
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Error dragging mouse on remote screen: " + ex.getMessage(), "Remote Screen Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    @Override
    public void keyPressed(KeyEvent e) {
        try {
            server.keyPressed(e.getKeyCode());
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Error sending key press to remote screen: " + ex.getMessage(), "Remote Screen Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        try {
            server.keyReleased(e.getKeyCode());
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, "Error sending key release to remote screen: " + ex.getMessage(), "Remote Screen Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    @Override
    public void mouseEntered(MouseEvent e) {

    }

    @Override
    public void mouseExited(MouseEvent e) {

    }


    @Override
    public void keyTyped(KeyEvent e) {
    }


    private void sendFileToServer() {
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                String filePath = fileChooser.getSelectedFile().getAbsolutePath();
                sendFile(filePath);
                JOptionPane.showMessageDialog(this, "File sent successfully!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error sending file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }

    public void sendFile(String filePath) throws RemoteException, IOException {
        File file = new File(filePath);
        byte[] fileData = Files.readAllBytes(Paths.get(file.getAbsolutePath()));
        server.sendFile(fileData, file.getName());
    }

    private class SendFileAction implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            int result = fileChooser.showOpenDialog(ClientUI.this);
            if (result == JFileChooser.APPROVE_OPTION) {
                try {
                    String filePath = fileChooser.getSelectedFile().getAbsolutePath();
                    byte[] fileData = Files.readAllBytes(Paths.get(filePath));
                    server.sendFile(fileData, fileChooser.getSelectedFile().getName());
                    JOptionPane.showMessageDialog(ClientUI.this, "Fichier envoyé avec succès !");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(ClientUI.this, "Erreur lors de l'envoi du fichier : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }
            }
        }
    }
    private class ReceiveFileAction implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            int result = fileChooser.showSaveDialog(ClientUI.this);
            if (result == JFileChooser.APPROVE_OPTION) {
                try {
                    String fileName = fileChooser.getSelectedFile().getName();
                    byte[] fileData = server.receiveFile(fileName);
                    FileOutputStream fos = new FileOutputStream(fileChooser.getSelectedFile());
                    fos.write(fileData);
                    fos.close();
                    JOptionPane.showMessageDialog(ClientUI.this, "Fichier reçu avec succès !");
                } catch ( IOException ex) {
                    JOptionPane.showMessageDialog(ClientUI.this, "Erreur lors de la réception du fichier : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }
            }
        }
    }
}